name: Webpack

on:
  workflow_dispatch:

  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install NPM Dependencies
        run: npm install

      - name: Build with Webpack
        run: npm run webpack

      - name: Dry Run NPM Publish
        run: npm publish --dry-run